# https://taskfile.dev

version: "3"

vars:
  BINARY_NAME: auth-server
  BUILD_DIR: bin

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Development
  dev:
    desc: Run in development mode
    env:
      GIN_MODE: debug
    cmds:
      - go run cmd/server/main.go

  # Build
  build:
    desc: Build production binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - CGO_ENABLED=0 go build -ldflags="-s -w" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} cmd/server/main.go

  run:
    desc: Run production binary
    deps: [build]
    env:
      GIN_MODE: release
    cmds:
      - ./{{.BUILD_DIR}}/{{.BINARY_NAME}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  # Testing
  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -cover -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test:short:
    desc: Run short tests only
    cmds:
      - go test -short ./...

  # Code quality
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - goimports -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  check:
    desc: Run all checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  # Dependencies
  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  deps:tidy:
    desc: Tidy dependencies
    cmds:
      - go mod tidy

  deps:update:
    desc: Update all dependencies
    cmds:
      - go get -u ./...
      - go mod tidy

  # Database
  db:up:
    desc: Start PostgreSQL container
    cmds:
      - docker compose up -d

  db:down:
    desc: Stop PostgreSQL container
    cmds:
      - docker compose down

  db:reset:
    desc: Reset database (delete all data)
    cmds:
      - docker compose down -v
      - docker compose up -d

  db:logs:
    desc: Show database logs
    cmds:
      - docker compose logs -f postgres

  # Docker
  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t template-go-auth:latest .

  docker:run:
    desc: Run Docker container
    cmds:
      - docker run --rm -p 8080:8080 --env-file .env --network host template-go-auth:latest

  docker:push:
    desc: Push Docker image (requires DOCKER_REGISTRY var)
    cmds:
      - docker tag template-go-auth:latest {{.DOCKER_REGISTRY}}/template-go-auth:latest
      - docker push {{.DOCKER_REGISTRY}}/template-go-auth:latest

  # Generate
  generate:
    desc: Run go generate
    cmds:
      - go generate ./...

  # CI/CD helpers
  ci:
    desc: Run CI pipeline locally
    cmds:
      - task: deps:tidy
      - task: fmt
      - task: vet
      - task: lint
      - task: test:coverage
      - task: build

  # Documentation
  docs:
    desc: Serve documentation locally (pkgsite)
    cmds:
      - echo "Documentation available at http://localhost:6060/github.com/cedev-1/template-go-auth"
      - go run golang.org/x/pkgsite/cmd/pkgsite@latest -http=:6060
